language: php

sudo: false

matrix:
  include:
    - php: 7.0
      env: WP_VERSION=4.6 WP_MULTISITE=0
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 7.1
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 7.2
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 7.2
      env: WP_VERSION=nightly WP_MULTISITE=0
  allow_failures:
    - php: 7.2
      env: WP_VERSION=nightly WP_MULTISITE=0
  fast_finish: true

before_script:
  - composer install
  - bash vendor/frozzare/wp-test-suite/bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 $WP_VERSION

script:
  - make lint
  - vendor/bin/phpunit --coverage-clover clover.xml